project:
  type: website



website:
  title: "AI for Chip Design"

  navbar:
    pinned: true

    left:
      - href: index.qmd
        text: Home
      - href: pages/cfp.qmd
        text: Call for Papers
      - href: pages/organizers.qmd
        text: Organizers
      - href: pages/speakers.qmd
        text: Speakers
      - href: pages/committee.qmd
        text: Program Committee
      - href: pages/sponsors.qmd
        text: Sponsors

    right:
      - href: pages/contact.qmd
        text: Contact

  page-footer:
    left: |
      AI for Chip Design — NeurIPS 2026 Workshop

    right: |
      [NeurIPS 2026](https://neurips.cc)

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
